[package]
name = "hpm-derive"
version = "0.1.0"
authors = ["Matthias Bussonnier <bussonniermatthias@gmail.com>"]

[dependencies]
syn = {version = "0.12", feature=["full", "extra-traits"]}
quote = "0.4.2"

[lib]
proc-macro = true
